from __future__ import annotations

from .http_json_response_protocol_part1 import HttpJsonResponseProtocolMixinPart1
from .http_json_response_protocol_part2 import HttpJsonResponseProtocolMixinPart2


class HttpJsonResponseProtocolMixin(HttpJsonResponseProtocolMixinPart1, HttpJsonResponseProtocolMixinPart2):
    pass
