from __future__ import annotations

from .http_json_error_handling_part1 import HttpJsonErrorHandlingMixinPart1
from .http_json_error_handling_part2 import HttpJsonErrorHandlingMixinPart2


class HttpJsonErrorHandlingMixin(HttpJsonErrorHandlingMixinPart1, HttpJsonErrorHandlingMixinPart2):
    pass
