from __future__ import annotations

from .provider_source_http_json_part1 import ProviderSourceHttpJsonMixinPart1
from .provider_source_http_json_part2 import ProviderSourceHttpJsonMixinPart2


class ProviderSourceHttpJsonMixin(ProviderSourceHttpJsonMixinPart1, ProviderSourceHttpJsonMixinPart2):
    pass
