from __future__ import annotations

from .registry_runtime_models_part1 import RegistryRuntimeModelsMixinPart1
from .registry_runtime_models_part2 import RegistryRuntimeModelsMixinPart2


class RegistryRuntimeModelsMixin(RegistryRuntimeModelsMixinPart1, RegistryRuntimeModelsMixinPart2):
    pass
