from __future__ import annotations

from .registry_http_json_projection_part1 import RegistryHttpJsonProjectionMixinPart1
from .registry_http_json_projection_part2 import RegistryHttpJsonProjectionMixinPart2


class RegistryHttpJsonProjectionMixin(RegistryHttpJsonProjectionMixinPart1, RegistryHttpJsonProjectionMixinPart2):
    pass
