from __future__ import annotations

from .registry_runtime_service_models_part1 import RegistryRuntimeServiceModelsMixinPart1
from .registry_runtime_service_models_part2 import RegistryRuntimeServiceModelsMixinPart2


class RegistryRuntimeServiceModelsMixin(RegistryRuntimeServiceModelsMixinPart1, RegistryRuntimeServiceModelsMixinPart2):
    pass
