from __future__ import annotations

from .task_session_export_payload_part1 import TaskSessionExportPayloadMixinPart1
from .task_session_export_payload_part2 import TaskSessionExportPayloadMixinPart2


class TaskSessionExportPayloadMixin(TaskSessionExportPayloadMixinPart1, TaskSessionExportPayloadMixinPart2):
    pass
