from __future__ import annotations

from .task_routes_usage_governance_part1 import TaskRoutesUsageGovernanceMixinPart1
from .task_routes_usage_governance_part2 import TaskRoutesUsageGovernanceMixinPart2


class TaskRoutesUsageGovernanceMixin(TaskRoutesUsageGovernanceMixinPart1, TaskRoutesUsageGovernanceMixinPart2):
    pass
