from __future__ import annotations

from .task_trace_export_governance_part1 import TaskTraceExportGovernanceMixinPart1
from .task_trace_export_governance_part2 import TaskTraceExportGovernanceMixinPart2


class TaskTraceExportGovernanceMixin(TaskTraceExportGovernanceMixinPart1, TaskTraceExportGovernanceMixinPart2):
    pass
