import { defaultSchema } from "rehype-sanitize";
import type { Schema } from "hast-util-sanitize";

/**
 * 扩展 GitHub 默认 schema，允许 rehype-highlight / rehype-katex 产出的 class 与部分 SVG/MathML。
 */
export const markdownSanitizeSchema: Schema = {
  ...defaultSchema,
  tagNames: [
    ...(defaultSchema.tagNames ?? []),
    "svg",
    "path",
    "line",
    "g",
    "rect",
    "polyline",
    "polygon",
    "circle",
    "ellipse",
    "foreignObject",
    "use",
    "math",
    "semantics",
    "mrow",
    "mi",
    "mn",
    "mo",
    "ms",
    "mspace",
    "mtext",
    "msup",
    "msub",
    "mfrac",
    "msubsup",
    "annotation",
    "annotation-xml",
  ],
  attributes: {
    ...defaultSchema.attributes,
    code: [
      ...(defaultSchema.attributes?.code ?? []),
      ["className", /^hljs/],
      ["className", /^language_/],
    ],
    span: [
      ["className", /^hljs/],
      ["className", /^katex/],
      "style",
      "ariaHidden",
    ],
    div: [
      ...(defaultSchema.attributes?.div ?? []),
      ["className", /^katex/],
      "style",
    ],
    math: ["xmlns", "display", "className"],
    semantics: ["className"],
    mrow: [],
    mi: ["mathVariant"],
    mn: [],
    mo: [
      "stretchy",
      "fence",
      "separator",
      "form",
      "symmetric",
      "largeop",
      "minsize",
      "maxsize",
    ],
    ms: [],
    mspace: ["width", "height", "depth"],
    mtext: [],
    msup: [],
    msub: [],
    mfrac: ["linethickness"],
    msubsup: [],
    annotation: ["encoding", "className"],
    "annotation-xml": ["encoding"],
    svg: [
      "xmlns",
      "width",
      "height",
      "viewBox",
      "preserveAspectRatio",
      "fill",
      "stroke",
      "className",
      "style",
      "ariaHidden",
    ],
    path: [
      "d",
      "fill",
      "stroke",
      "strokeWidth",
      "strokeLinecap",
      "strokeLinejoin",
      "transform",
    ],
    line: ["x1", "y1", "x2", "y2", "stroke", "strokeWidth"],
    g: ["className", "style", "transform", "fill", "stroke"],
    rect: ["x", "y", "width", "height", "fill", "stroke", "rx", "ry"],
    polyline: ["points", "fill", "stroke"],
    polygon: ["points", "fill", "stroke"],
    circle: ["cx", "cy", "r", "fill", "stroke"],
    ellipse: ["cx", "cy", "rx", "ry", "fill", "stroke"],
    foreignObject: ["width", "height", "x", "y"],
    use: ["href", "x", "y", "width", "height"],
  },
};
